# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\ndemo.proto\"\x0f\n\x01\x42\x12\n\n\x02\x62\x32\x18\x02 \x01(\t\"\x1e\n\x01\x41\x12\r\n\x01\x62\x18\x01 \x01(\x0b\x32\x02.B\x12\n\n\x02id\x18\x02 \x01(\t')
)




_B = _descriptor.Descriptor(
  name='B',
  full_name='B',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b2', full_name='B.b2', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=29,
)


_A = _descriptor.Descriptor(
  name='A',
  full_name='A',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b', full_name='A.b', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='A.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=61,
)

_A.fields_by_name['b'].message_type = _B
DESCRIPTOR.message_types_by_name['B'] = _B
DESCRIPTOR.message_types_by_name['A'] = _A
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

B = _reflection.GeneratedProtocolMessageType('B', (_message.Message,), dict(
  DESCRIPTOR = _B,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:B)
  ))
_sym_db.RegisterMessage(B)

A = _reflection.GeneratedProtocolMessageType('A', (_message.Message,), dict(
  DESCRIPTOR = _A,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:A)
  ))
_sym_db.RegisterMessage(A)


# @@protoc_insertion_point(module_scope)
